### ISSUE TITLE
sendSDKMessage is very slow

### ISSUE THREAD

**Issue by flufy3d** [Unity-Technologies/furioos-sdk-js#16] opened 2020-08-17 09:22 UTC
almost have one second delay

**Comment by flufy3d** [comment] 2020-08-17 09:43
I checked the code 
I found all message need route to portal.furioos.com first
then send to the eu render machine.
that leads the slow.
but I found the native control is very fast I guess that is based on webrtc datachannel.
could you guy rewrite the sdk send and recv base on webrtc datachannel?

**Comment by DonJGo** [comment] 2020-09-23 08:46
Hi

Thanks again for your report and to be active on the SDK :)
Indeed we have sometimes see that the messages were slow.
We are working on it.

You describe well the process.
Just want to add some precisions.
We have to deal with portal.furioos.com to send messages to the machin through the datachannel.
All our events and SDK massages are using the datachannel as the native controls.

So there is probably nothing to rewrite here.
The problem should come from somewhere else.

Thank you again for helping us improving the SDK.
Regards.

**Comment by flufy3d** [comment] 2020-09-23 09:46
cool ,Thank you for your reply and look forward to the fix of this issue

**Comment by K-MICK** [comment] 2020-12-01 10:18
I close the issue, the problem is fixed since the last update.

**Closed** 2020-12-01 10:18 UTC
